[package]
name = "drand-verify"
version = "0.1.0"
authors = ["Simon Warta <simon@warta.it>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paired = { path = "../pairing" }
sha2 = "0.8"
hex-literal = "0.3.1"
hex = "0.4"